// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client_message.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_client_5fmessage_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_client_5fmessage_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_client_5fmessage_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_client_5fmessage_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_client_5fmessage_2eproto;
namespace sockets {
class client_msg;
struct client_msgDefaultTypeInternal;
extern client_msgDefaultTypeInternal _client_msg_default_instance_;
}  // namespace sockets
PROTOBUF_NAMESPACE_OPEN
template<> ::sockets::client_msg* Arena::CreateMaybeMessage<::sockets::client_msg>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace sockets {

enum client_msg_OperationType : int {
  client_msg_OperationType_PUT = 0,
  client_msg_OperationType_GET = 1
};
bool client_msg_OperationType_IsValid(int value);
constexpr client_msg_OperationType client_msg_OperationType_OperationType_MIN = client_msg_OperationType_PUT;
constexpr client_msg_OperationType client_msg_OperationType_OperationType_MAX = client_msg_OperationType_GET;
constexpr int client_msg_OperationType_OperationType_ARRAYSIZE = client_msg_OperationType_OperationType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* client_msg_OperationType_descriptor();
template<typename T>
inline const std::string& client_msg_OperationType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, client_msg_OperationType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function client_msg_OperationType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    client_msg_OperationType_descriptor(), enum_t_value);
}
inline bool client_msg_OperationType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, client_msg_OperationType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<client_msg_OperationType>(
    client_msg_OperationType_descriptor(), name, value);
}
// ===================================================================

class client_msg final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sockets.client_msg) */ {
 public:
  inline client_msg() : client_msg(nullptr) {}
  ~client_msg() override;
  explicit PROTOBUF_CONSTEXPR client_msg(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  client_msg(const client_msg& from);
  client_msg(client_msg&& from) noexcept
    : client_msg() {
    *this = ::std::move(from);
  }

  inline client_msg& operator=(const client_msg& from) {
    CopyFrom(from);
    return *this;
  }
  inline client_msg& operator=(client_msg&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const client_msg& default_instance() {
    return *internal_default_instance();
  }
  static inline const client_msg* internal_default_instance() {
    return reinterpret_cast<const client_msg*>(
               &_client_msg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(client_msg& a, client_msg& b) {
    a.Swap(&b);
  }
  inline void Swap(client_msg* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(client_msg* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  client_msg* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<client_msg>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const client_msg& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const client_msg& from) {
    client_msg::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(client_msg* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sockets.client_msg";
  }
  protected:
  explicit client_msg(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef client_msg_OperationType OperationType;
  static constexpr OperationType PUT =
    client_msg_OperationType_PUT;
  static constexpr OperationType GET =
    client_msg_OperationType_GET;
  static inline bool OperationType_IsValid(int value) {
    return client_msg_OperationType_IsValid(value);
  }
  static constexpr OperationType OperationType_MIN =
    client_msg_OperationType_OperationType_MIN;
  static constexpr OperationType OperationType_MAX =
    client_msg_OperationType_OperationType_MAX;
  static constexpr int OperationType_ARRAYSIZE =
    client_msg_OperationType_OperationType_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  OperationType_descriptor() {
    return client_msg_OperationType_descriptor();
  }
  template<typename T>
  static inline const std::string& OperationType_Name(T enum_t_value) {
    static_assert(::std::is_same<T, OperationType>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function OperationType_Name.");
    return client_msg_OperationType_Name(enum_t_value);
  }
  static inline bool OperationType_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      OperationType* value) {
    return client_msg_OperationType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kSourceTypeFieldNumber = 2,
    kValueFieldNumber = 4,
    kOperationFieldNumber = 1,
    kKeyFieldNumber = 3,
    kPortFieldNumber = 5,
    kSuccessFieldNumber = 6,
  };
  // optional string source_type = 2;
  bool has_source_type() const;
  private:
  bool _internal_has_source_type() const;
  public:
  void clear_source_type();
  const std::string& source_type() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_source_type(ArgT0&& arg0, ArgT... args);
  std::string* mutable_source_type();
  PROTOBUF_NODISCARD std::string* release_source_type();
  void set_allocated_source_type(std::string* source_type);
  private:
  const std::string& _internal_source_type() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_source_type(const std::string& value);
  std::string* _internal_mutable_source_type();
  public:

  // optional string value = 4;
  bool has_value() const;
  private:
  bool _internal_has_value() const;
  public:
  void clear_value();
  const std::string& value() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_value(ArgT0&& arg0, ArgT... args);
  std::string* mutable_value();
  PROTOBUF_NODISCARD std::string* release_value();
  void set_allocated_value(std::string* value);
  private:
  const std::string& _internal_value() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_value(const std::string& value);
  std::string* _internal_mutable_value();
  public:

  // optional .sockets.client_msg.OperationType operation = 1;
  bool has_operation() const;
  private:
  bool _internal_has_operation() const;
  public:
  void clear_operation();
  ::sockets::client_msg_OperationType operation() const;
  void set_operation(::sockets::client_msg_OperationType value);
  private:
  ::sockets::client_msg_OperationType _internal_operation() const;
  void _internal_set_operation(::sockets::client_msg_OperationType value);
  public:

  // optional int32 key = 3;
  bool has_key() const;
  private:
  bool _internal_has_key() const;
  public:
  void clear_key();
  int32_t key() const;
  void set_key(int32_t value);
  private:
  int32_t _internal_key() const;
  void _internal_set_key(int32_t value);
  public:

  // optional int32 port = 5;
  bool has_port() const;
  private:
  bool _internal_has_port() const;
  public:
  void clear_port();
  int32_t port() const;
  void set_port(int32_t value);
  private:
  int32_t _internal_port() const;
  void _internal_set_port(int32_t value);
  public:

  // optional int32 success = 6;
  bool has_success() const;
  private:
  bool _internal_has_success() const;
  public:
  void clear_success();
  int32_t success() const;
  void set_success(int32_t value);
  private:
  int32_t _internal_success() const;
  void _internal_set_success(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:sockets.client_msg)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr source_type_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr value_;
    int operation_;
    int32_t key_;
    int32_t port_;
    int32_t success_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_client_5fmessage_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// client_msg

// optional .sockets.client_msg.OperationType operation = 1;
inline bool client_msg::_internal_has_operation() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool client_msg::has_operation() const {
  return _internal_has_operation();
}
inline void client_msg::clear_operation() {
  _impl_.operation_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::sockets::client_msg_OperationType client_msg::_internal_operation() const {
  return static_cast< ::sockets::client_msg_OperationType >(_impl_.operation_);
}
inline ::sockets::client_msg_OperationType client_msg::operation() const {
  // @@protoc_insertion_point(field_get:sockets.client_msg.operation)
  return _internal_operation();
}
inline void client_msg::_internal_set_operation(::sockets::client_msg_OperationType value) {
  assert(::sockets::client_msg_OperationType_IsValid(value));
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.operation_ = value;
}
inline void client_msg::set_operation(::sockets::client_msg_OperationType value) {
  _internal_set_operation(value);
  // @@protoc_insertion_point(field_set:sockets.client_msg.operation)
}

// optional string source_type = 2;
inline bool client_msg::_internal_has_source_type() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool client_msg::has_source_type() const {
  return _internal_has_source_type();
}
inline void client_msg::clear_source_type() {
  _impl_.source_type_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& client_msg::source_type() const {
  // @@protoc_insertion_point(field_get:sockets.client_msg.source_type)
  return _internal_source_type();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void client_msg::set_source_type(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000001u;
 _impl_.source_type_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:sockets.client_msg.source_type)
}
inline std::string* client_msg::mutable_source_type() {
  std::string* _s = _internal_mutable_source_type();
  // @@protoc_insertion_point(field_mutable:sockets.client_msg.source_type)
  return _s;
}
inline const std::string& client_msg::_internal_source_type() const {
  return _impl_.source_type_.Get();
}
inline void client_msg::_internal_set_source_type(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.source_type_.Set(value, GetArenaForAllocation());
}
inline std::string* client_msg::_internal_mutable_source_type() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.source_type_.Mutable(GetArenaForAllocation());
}
inline std::string* client_msg::release_source_type() {
  // @@protoc_insertion_point(field_release:sockets.client_msg.source_type)
  if (!_internal_has_source_type()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* p = _impl_.source_type_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.source_type_.IsDefault()) {
    _impl_.source_type_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void client_msg::set_allocated_source_type(std::string* source_type) {
  if (source_type != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.source_type_.SetAllocated(source_type, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.source_type_.IsDefault()) {
    _impl_.source_type_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:sockets.client_msg.source_type)
}

// optional int32 key = 3;
inline bool client_msg::_internal_has_key() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool client_msg::has_key() const {
  return _internal_has_key();
}
inline void client_msg::clear_key() {
  _impl_.key_ = 0;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline int32_t client_msg::_internal_key() const {
  return _impl_.key_;
}
inline int32_t client_msg::key() const {
  // @@protoc_insertion_point(field_get:sockets.client_msg.key)
  return _internal_key();
}
inline void client_msg::_internal_set_key(int32_t value) {
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.key_ = value;
}
inline void client_msg::set_key(int32_t value) {
  _internal_set_key(value);
  // @@protoc_insertion_point(field_set:sockets.client_msg.key)
}

// optional string value = 4;
inline bool client_msg::_internal_has_value() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool client_msg::has_value() const {
  return _internal_has_value();
}
inline void client_msg::clear_value() {
  _impl_.value_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& client_msg::value() const {
  // @@protoc_insertion_point(field_get:sockets.client_msg.value)
  return _internal_value();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void client_msg::set_value(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000002u;
 _impl_.value_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:sockets.client_msg.value)
}
inline std::string* client_msg::mutable_value() {
  std::string* _s = _internal_mutable_value();
  // @@protoc_insertion_point(field_mutable:sockets.client_msg.value)
  return _s;
}
inline const std::string& client_msg::_internal_value() const {
  return _impl_.value_.Get();
}
inline void client_msg::_internal_set_value(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.value_.Set(value, GetArenaForAllocation());
}
inline std::string* client_msg::_internal_mutable_value() {
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.value_.Mutable(GetArenaForAllocation());
}
inline std::string* client_msg::release_value() {
  // @@protoc_insertion_point(field_release:sockets.client_msg.value)
  if (!_internal_has_value()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* p = _impl_.value_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.value_.IsDefault()) {
    _impl_.value_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void client_msg::set_allocated_value(std::string* value) {
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.value_.SetAllocated(value, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.value_.IsDefault()) {
    _impl_.value_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:sockets.client_msg.value)
}

// optional int32 port = 5;
inline bool client_msg::_internal_has_port() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool client_msg::has_port() const {
  return _internal_has_port();
}
inline void client_msg::clear_port() {
  _impl_.port_ = 0;
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline int32_t client_msg::_internal_port() const {
  return _impl_.port_;
}
inline int32_t client_msg::port() const {
  // @@protoc_insertion_point(field_get:sockets.client_msg.port)
  return _internal_port();
}
inline void client_msg::_internal_set_port(int32_t value) {
  _impl_._has_bits_[0] |= 0x00000010u;
  _impl_.port_ = value;
}
inline void client_msg::set_port(int32_t value) {
  _internal_set_port(value);
  // @@protoc_insertion_point(field_set:sockets.client_msg.port)
}

// optional int32 success = 6;
inline bool client_msg::_internal_has_success() const {
  bool value = (_impl_._has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool client_msg::has_success() const {
  return _internal_has_success();
}
inline void client_msg::clear_success() {
  _impl_.success_ = 0;
  _impl_._has_bits_[0] &= ~0x00000020u;
}
inline int32_t client_msg::_internal_success() const {
  return _impl_.success_;
}
inline int32_t client_msg::success() const {
  // @@protoc_insertion_point(field_get:sockets.client_msg.success)
  return _internal_success();
}
inline void client_msg::_internal_set_success(int32_t value) {
  _impl_._has_bits_[0] |= 0x00000020u;
  _impl_.success_ = value;
}
inline void client_msg::set_success(int32_t value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:sockets.client_msg.success)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace sockets

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::sockets::client_msg_OperationType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::sockets::client_msg_OperationType>() {
  return ::sockets::client_msg_OperationType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_client_5fmessage_2eproto
